[project]
name = "rag-mtg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "python-dotenv>=1.2.1",
    "llama-index-vector-stores-chroma>=0.5.3",
    "openai>=2.8.1",
    "llama-index>=0.14.8",
    "pypdf>=6.4.0",
    "streamlit>=1.51.0",
]
